import os
import logging
from typing import Dict, Any
import pandas as pd

from config import BACKTESTER_CONFIG  # Updated import
from src.core.etl.loader import load_base_data
from src.core.strat_stats.statistics import (
    save_base_file,
    save_trade_file,
    calculate_metrics,
    save_summary_file
)
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.strategies.strategy_factory import StrategyFactory
from src.strategies.register_strategies import register_all_strategies

def execute_strategy(ticker: str, pull_date: str, strategy_name: str) -> Dict[str, Any]:
    """
    1) Load base data
    2) Execute the strategy
    3) Get trades directly from strategy
    4) Save _Base_ and _Trades_ files
    5) Append to _Summary_ if needed
    """
    logging.info(f"Executing strategy '{strategy_name}' for {ticker} on {pull_date}")

    # 1) Load data - use multi-timeframe loader for MSE strategy
    from src.core.etl.loader import load_multi_timeframe_data
    try:
        # MSE strategy needs 5m and 15m data
        multi_data = load_multi_timeframe_data(pull_date, [ticker], ['5m', '15m'])
        if not multi_data or ticker not in multi_data:
            logging.warning(f"No multi-timeframe data loaded for {ticker} on {pull_date}. Skipping.")
            return {}
        
        base_data = multi_data[ticker]
        if not base_data or all(df.empty for df in base_data.values()):
            logging.warning(f"All timeframe data is empty for {ticker} on {pull_date}. Skipping.")
            return {}
            
        logging.info(f"Loaded multi-timeframe data for {ticker}: {list(base_data.keys())}")
    except Exception as e:
        logging.error(f"Failed to load multi-timeframe data for {ticker}: {e}")
        return {}

    # 2) Get strategy instance from factory
    from src.strategies.strategy_factory import StrategyFactory
    strategy = StrategyFactory.create_strategy(strategy_name)
    if strategy is None:
        logging.error(f"Strategy '{strategy_name}' not found in factory.")
        return {}

    # 3) Prepare data with indicators
    try:
        prepared_data = strategy.prepare_data(base_data, ticker, pull_date)
        logging.info(f"Data prepared for {ticker} with strategy {strategy_name}")
    except Exception as e:
        logging.error(f"Failed to prepare data for {ticker}: {e}")
        return {}

    # 4) Generate signals from multi-timeframe data
    try:
        signals_df = strategy.generate_signals(prepared_data)
        logging.info(f"Signals generated for {ticker}: {len(signals_df)} records")
    except Exception as e:
        logging.error(f"Signal generation failed for {ticker}: {e}")
        return {}

    # 5) Execute strategy to get trades directly
    try:
        trades_df, summary_stats = strategy.execute_strategy(signals_df, initial_capital=100000)
        if trades_df is None or trades_df.empty:
            logging.warning(f"No trades generated by strategy for {ticker} on {pull_date}")
            trades = []
        else:
            # Convert trades DataFrame to list format for compatibility
            trades = trades_df.to_dict('records')
            logging.info(f"Strategy generated {len(trades)} trades for {ticker}")
    except Exception as e:
        logging.error(f"Strategy execution failed for {ticker}: {e}")
        return {}

    # 6) Save base & trades files
    strategy_output_folder = os.path.join(
        BACKTESTER_CONFIG['OUTPUT_FOLDER'], 
        strategy_name, 
        pull_date
    )
    os.makedirs(strategy_output_folder, exist_ok=True)

    # Save base data - use the signals dataframe which contains all the indicators
    base_df_to_save = signals_df
        
    base_file = os.path.join(strategy_output_folder, f"{ticker}_Base_{pull_date}.csv")
    print(f"{ticker}_Base_{pull_date}.csv", ", Saved")
    save_base_file(base_df_to_save, base_file)

    # Save trades
    trade_file = os.path.join(strategy_output_folder, f"{ticker}_Trades_{pull_date}.csv")
    print(f"{ticker}_Trades_{pull_date}.csv", ", Saved")
    save_trade_file(trades, trade_file)

    # 7) Compute metrics & append to summary
    if trades:
        metrics = calculate_metrics(trades)
        metrics["Ticker"] = ticker
        metrics["Strategy"] = strategy_name
        metrics["Pull Date"] = pull_date
        logging.info(f"Calculated metrics for {ticker}: {len(trades)} trades")
    else:
        metrics = {
            "Ticker": ticker,
            "Strategy": strategy_name,
            "Pull Date": pull_date,
            "Total Trades": 0,
            "Winning Trades": 0,
            "Total Return": 0.0
        }
        logging.warning(f"No trades found for {ticker} - using default metrics")

    summary_file = os.path.join(strategy_output_folder, f"{pull_date}_Summary.csv")
    save_summary_file(metrics, summary_file)

    return metrics

def extract_trades(df: pd.DataFrame) -> list:
    """
    Iterates through the strategy DataFrame row‐by‐row to detect trade entry and exit signals.
    This updated version also records:
      - "High Time": the timestamp when the highest price (for buy trades) was reached.
      - "Low Time": the timestamp when the lowest price (for buy trades) was reached.
      - "Trade Duration (min)": the time in minutes from entry to exit.
    For sell trades, the logic is similar but the extreme is reversed.
    """
    trades = []
    in_buy_trade = False
    in_sell_trade = False
    trade = {}

    for idx, row in df.iterrows():
        # Check for BUY entry if no trade is active.
        if not in_buy_trade and not in_sell_trade and row.get("entry_signal_buy"):
            in_buy_trade = True
            trade = {
                "Trade Type": "Buy",
                "Entry Time": row["timestamp"],
                "Entry Price": row["close"],
                "High During Trade": row["close"],
                "Low During Trade": row["close"],
                "High Time": row["timestamp"],
                "Low Time": row["timestamp"],
            }
        # Check for SELL entry if no trade is active.
        elif not in_buy_trade and not in_sell_trade and row.get("entry_signal_sell"):
            in_sell_trade = True
            trade = {
                "Trade Type": "Sell",
                "Entry Time": row["timestamp"],
                "Entry Price": row["close"],
                "High During Trade": row["close"],
                "Low During Trade": row["close"],
                "High Time": row["timestamp"],
                "Low Time": row["timestamp"],
            }
        
        # If in a BUY trade, update high/low values and their timestamps.
        if in_buy_trade:
            if row["close"] > trade["High During Trade"]:
                trade["High During Trade"] = row["close"]
                trade["High Time"] = row["timestamp"]
            if row["close"] < trade["Low During Trade"]:
                trade["Low During Trade"] = row["close"]
                trade["Low Time"] = row["timestamp"]
            if row.get("exit_signal_buy"):
                trade["Exit Time"] = row["timestamp"]
                trade["Exit Price"] = row["close"]
                trade["Profit (Currency)"] = trade["Exit Price"] - trade["Entry Price"]
                trade["Profit (%)"] = (100 * trade["Profit (Currency)"] / trade["Entry Price"]
                                       if trade["Entry Price"] != 0 else 0)
                # Calculate trade duration in minutes.
                entry_time = pd.to_datetime(trade["Entry Time"])
                exit_time = pd.to_datetime(trade["Exit Time"])
                trade["Trade Duration (min)"] = round((exit_time - entry_time).total_seconds() / 60, 2)
                trades.append(trade)
                in_buy_trade = False
                trade = {}
        
        # If in a SELL trade, update high/low values and their timestamps.
        if in_sell_trade:
            if row["close"] < trade["Low During Trade"]:
                trade["Low During Trade"] = row["close"]
                trade["Low Time"] = row["timestamp"]
            if row["close"] > trade["High During Trade"]:
                trade["High During Trade"] = row["close"]
                trade["High Time"] = row["timestamp"]
            if row.get("exit_signal_sell"):
                trade["Exit Time"] = row["timestamp"]
                trade["Exit Price"] = row["close"]
                trade["Profit (Currency)"] = trade["Entry Price"] - trade["Exit Price"]
                trade["Profit (%)"] = (100 * trade["Profit (Currency)"] / trade["Entry Price"]
                                       if trade["Entry Price"] != 0 else 0)
                entry_time = pd.to_datetime(trade["Entry Time"])
                exit_time = pd.to_datetime(trade["Exit Time"])
                trade["Trade Duration (min)"] = round((exit_time - entry_time).total_seconds() / 60, 2)
                trades.append(trade)
                in_sell_trade = False
                trade = {}
                
    return trades
